### ISSUE TITLE
Tenter une collecte à partir des certificate transparency logs

### ISSUE THREAD

**Issue by JulienPalard** [etalab/noms-de-domaine-organismes-publics#15]
crt.sh expose un postgresql public des [Certificate Transparency logs](https://en.wikipedia.org/wiki/Certificate_Transparency) (`psql -h crt.sh certwatch guest`), en partant de là on peut tenter deux choses :

- Importer d'un coup les domaines connus dans les CT logs.
- Ajouter périodiquement les nouveaux domaines apparaissant dans ces logs.

**Comment by JulienPalard** [comment]
Did another one, it works well, so I'm closing this issue. I "documented" the procedure in the commit message.

**Comment by bzg** [comment]
Thanks!
