### ISSUE TITLE
https://mesdemarches.emploi.gouv.fr est down

### ISSUE THREAD

**Issue by JulienPalard** [etalab/noms-de-domaine-organismes-publics#21]
Ce n'est clairement pas le rôle de ce repo, mais ça pourrait être un projet qui l'utilise, de surveiller l'uptime des sites des administrations publiques.

Si jamais ce projet voyait le jour, il nous faudrait un moyen de contacter les bonnes personnes, pour prendre l'exemple d'aujourd'hui je n'ai aucune idée de qui contacter pour mesdemarches.emploi.gouv.fr.

Ça semble être géré par la DGEFP mais https://lannuaire.service-public.fr/gouvernement/administration-centrale-ou-ministere_171944 ne donne pas de contact technique.

**Comment by bzg** [comment]
Salut @JulienPalard - merci pour l'issue.  Du coup, si on souhaite se servir des issues de ce dépôt pour répertorier des idées de services qu'on pourrait proposer à partir de cette liste de noms de domaine, je propose que le titre de l'issue corresponde à l'idée de service (plutôt qu'à un bug qui remonterait grâce au service.)

Est-ce que tu es OK avec l'approche ?  Si oui, je te laisse fermer cette issue, en ouvrir une autre avec l'idée de service et créer une catégorie dédiée pour ces issues ?

**Comment by JulienPalard** [comment]
Je profitais de l'exemple : j'aime bien expérimenter une idée « manuellement » avant d'essayer d'automatiser quoi que ce soit, pour me faire une première idée du côté réalisable ou non de l'idée, mais avec du recul tu as raison c'est plus digeste si l'issue parle du service et non du problème.

**Comment by JulienPalard** [comment]
(il ne me semble pas avoir le droit de créer de catégories de tickets)

**Comment by bzg** [comment]
Je t'ai mis en mainteneur du dépôt: est-ce que c'est OK?

**Comment by JulienPalard** [comment]
C'est OK !
