### ISSUE TITLE
Informations manquantes dans le README

### ISSUE THREAD

**Issue by johanricher** [etalab/noms-de-domaine-organismes-publics#28]
Bonjour

J'ai découvert ce projet qui pourrait potentiellement répondre à des besoins très nombreux. Je trouve que c'est une initiative de référentiel particulièrement intéressante donc tout d'abord merci à ses contributrices et contributeurs !

Pour moi il manque 2 choses pour favoriser les contributions extérieures comme la mienne :
* La définition du périmètre de ce référentiel : qu'est-ce qui peut être ajouté ? La notion d' "organisme remplissant des missions de service public" devrait selon moi être précisée et objectivée. Idéalement elle devrait être associée à un autre référentiel du [SPD](https://www.data.gouv.fr/fr/pages/spd/reference/) comme le SIRET d'un établissement public dans SIRENE. Même si je peux comprendre que c'est mettre la charrue avant les boeufs, il peut être utile à ce stade de poser un cadre quitte à ne pas le respecter complètement au début.
* La liste des usages actuel de ce référentiel (ou des exemples) : à quoi/qui il sert ? ça permettrait aussi de justifier le périmètre du référentiel (dans quel but il a été établi de cette façon) et donc de répondre indirectement au premier point.

Vous l'avez compris, ce sont des remarques sur la forme et pas du tout sur le fond, mon but n'est pas de mettre en question l'existence même du projet ni la façon de le faire. :)

**Comment by JulienPalard** [comment]
Bonjour @johanricher, merci d'avoir pris le temps de rédiger cette issue !

> La définition du périmètre de ce référentiel : qu'est-ce qui peut être ajouté ?

C'est une question qu'on se pose tous je crois, merci d'aborder le sujet !

La définition que je me suis forgé au fil de mes contributions ressemble à :

- Si le nom de domaine est financé par des deniers publics, c'est bon pour moi.
- Sinon si le contenu délivré est produit par des deniers publics, c'est bon pour moi.
- Sinon c'est pas bon.

(Mes choix de mots ne sont pas parfaits, les deniers publics ne produisent pas de contenu : le contenu est produit par des humains payés par des deniers publics, il faudrait re-phraser ça...)

Je te laisse aller lire https://github.com/etalab/noms-de-domaine-organismes-publics/issues/26 sur le même sujet.

Malheureusement ce n'est que **ma** définition, selon **mes critères personnels** (je suis moi-même un contributeur externe, je contribue la nuit sur mon temps libre), elle ne vaut pas grand-chose, mais on peut peut-être partir de là et améliorer jusqu'à un consensus, @bzg tu as peut-être quelque chose à rajouter, ou un contact qui pourrait relire ça ?

> La liste des usages actuels de ce référentiel (ou des exemples) : à quoi/qui il sert ?

@villesinternet, @kuczynski, @revolunet  ^  vous voulez faire une PR ?

**Comment by bzg** [comment]
Julien Palard ***@***.***> writes:

> La définition que je me suis forgé au fil de mes contributions ressemble à :
>
>     Si le nom de domaine est financé par des deniers publics, c'est bon pour moi.
>     Sinon si le contenu délivré est produit par des deniers publics, c'est bon pour moi.
>     Sinon c'est pas bon.

Oui : pour tout domaine listé dans ce jeu de données, il a été acquis ou créé par ou pour un organisme public, et les contenus exposés sur une URL publique associé au nom de domaine sont sous la responsabilité éditoriale d'un organisme public.

etalab.gouv.fr a été acheté par un service du premier ministre.

mairietruc.blogspot.com a été créé par ou pour un organisme public.

Les contenus exposés sur etalab.gouv.fr et sur mairietruc.blogspot.com sont sous la responsabilité éditoriale d'un organisme public.

Nous devons évacuer la question des intermédiaire techniques pour l'achat ou de la mise en ligne des contenus, qui ne compte pas.

>     La liste des usages actuels de ce référentiel (ou des exemples) : à quoi/qui il sert ?
>    
> @villesinternet, @kuczynski, @revolunet ^ vous voulez faire une PR ?

C'est un aspect à mettre en avant le README.

Pour l'instant, il y a beaucoup d'usages qui ne sont que potentiels, mais l'idée est de stabiliser le repo pour qu'il leur permette de s'en servir comme source pour ces usages.
